<%@ Page Language="C#" AutoEventWireup="true" CodeFile="edit.aspx.cs" Inherits="admin_edit" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="qid" HeaderText="qid" InsertVisible="False" 
                ReadOnly="True" SortExpression="qid" />
            <asp:BoundField DataField="qno" HeaderText="qno" SortExpression="qno" />
            <asp:BoundField DataField="que" HeaderText="que" SortExpression="que" />
            <asp:BoundField DataField="opA" HeaderText="opA" SortExpression="opA" />
            <asp:BoundField DataField="opB" HeaderText="opB" SortExpression="opB" />
            <asp:BoundField DataField="opC" HeaderText="opC" SortExpression="opC" />
            <asp:BoundField DataField="opD" HeaderText="opD" SortExpression="opD" />
            <asp:BoundField DataField="correct" HeaderText="correct" 
                SortExpression="correct" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OTSConnectionString %>" 
        
        SelectCommand="SELECT [qid], [qno], [que], [opA], [opB], [opC], [opD], [correct] FROM [qtabel1]" 
        DeleteCommand="DELETE FROM qtabel1 WHERE (qid = @qid)" 
        UpdateCommand="UPDATE qtabel1 SET qno = @qno, que = @que, opA = @opA, opB = @opB, opC = @opC, opD = @opD, correct = @correct WHERE (qid = @qid)">
        <DeleteParameters>
            <asp:Parameter Name="qid" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="qno" />
            <asp:Parameter Name="que" />
            <asp:Parameter Name="opA" />
            <asp:Parameter Name="opB" />
            <asp:Parameter Name="opC" />
            <asp:Parameter Name="opD" />
            <asp:Parameter Name="correct" />
            <asp:Parameter Name="qid" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </form>
</body>
</html>
